### ISSUE TITLE
Call a .NET quartz console app job from .NET Web API

### ISSUE THREAD

**Issue by aniljain100** [adometry/QuartzNetManager#2]
Hi,

I have a .NET console quartz job running and I would like to interrupt or trigger this job from a different client (.NET Web API).

Please help me with samples.

Thanks
Anil Jain

**Comment by srjkumbhar** [comment]
Dear Anjali,

If you want to trigger or schedule console, you can achieve this using windows task manager.

Alternately please provide few additional details to get the suggestions.

Thanks!
Suraj

**Comment by aniljain100** [comment]
Hi Suraj,

Thanks for your reply. 

Please note my name is Anil Jain and not Anjali  :)

Windows manager is not a feasible option to me.
I would like to trigger this manually. May be at the click of a button on a .NET winform or a ASP.NET web page button.

Please let me know what details you need.

Thanks
Anil Jain

**Comment by aniljain100** [comment]
Closing the issue as its not required any more.
